workflows:
  my-workflow:
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache  
    instance_type: mac_pro
    scripts:
      - name: say hello
        script: echo "Hello Codemagician!"
        
      - name: Build Android APK
        working_directory: android
        script: flutter build apk --release
    artifacts:
      - app/build/outputs/test.apk     
    environment:
      flutter: stable
