workflows:
  work-flow1:
    name: build apk 
    environment:
      groups:
        - keystore_credentials
        - app_store_credentials
        - manual_cert_credentials
        - firebase_credentials
        - other

      flutter: stable   
      xcode: latest    
      cocoapods: 1.9.1  
     


    scripts:
      - echo "single line script"

      - name: Build for iOS
        script: flutter build ios
      - name: Build for Android
        script: flutter build apl --release
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - alieid19961996@gmail.com

