workflows:
  work-flow1:
    name: build apk 
    scripts:
        - echo "Hello World!"
    labels:
      - QA
      - ${TENANT_NAME}
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:             # Define your environment variables groups here
      	- keystore_credentials
      	- app_store_credentials
       	- manual_cert_credentials
    	  - firebase_credentials
    	  - other
      vars:		# Define your environment variables here
        PUBLIC_ENV_VAR: "value here"
      flutter: stable   # Define the channel name, version (e.g. v1.13.4), or fvm for Flutter Version Management
      xcode: latest     # Define latest, edge or version (e.g. 11.2)
      cocoapods: 1.9.1  # Define default or version
      node: 12.14.0     # Define default, latest, current, lts, carbon (or another stream), nightly or version
      npm: 6.13.7       # Define default, latest, next, lts or version
      ndk: r21d         # Define default or revision (e.g. r19c)
      java: 1.8         # Define default, or platform version (e.g. 11)
      ruby: 2.7.2       # Define default or version

    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - echo "single line script"
      - name: Flutter test
        script: flutter test
        ignore_failure: true
      - | 
        #!/usr/bin/env python3

        print('Multiline python script')
      - name: Build for iOS
        script: flutter build ios
      - name: Build for Android
        script: flutter build apl --release
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - alieid19961996@gmail.com
      scripts:
        - name: Report build status
        script: | 
          if [ -a "~/SUCCESS" ] ; then
           # build successful
          else
           # build failed
          fi
