workflows:
  work-flow1:
    name: build apk 


    max_build_duration: 60
    environment:
      groups:
        - keystore_credentials
        - app_store_credentials
        - manual_cert_credentials
        - firebase_credentials
        - other
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: stable   
      xcode: latest    
      cocoapods: 1.9.1  
      npm: 6.13.7   
      node: 12.14.0         
      ndk: r21d         
      java: 1.8         
      ruby: 2.7.2      

    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - echo "single line script"
      - name: Flutter test
        script: flutter test
        ignore_failure: true
      - | 
        #!/usr/bin/env python3

        print('Multiline python script')
      - name: Build for iOS
        script: flutter build ios
      - name: Build for Android
        script: flutter build apl --release
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - alieid19961996@gmail.com
      scripts:
       - name: Report build status
         script: | 
          if [ -a "~/SUCCESS" ] ; then
           # build successful
          else
           # build failed
          fi
