workflows:
  my-workflow:
    triggering:
      events:
        - push
      branch_patterns: 
        - pattern: develop
          include: false
      cancel_previous_builds: true

    publishing:
      email:
        recipients:
          - alieid19961996@gmail.com

    scripts:
      - name: say hello
        script: echo "Hello Codemagician!"

      - name: Build Android App Bundle
        working_directory: android
        script: ./gradlew bundleRelease
      - name: Build Android APK
        working_directory: android
        script: ./gradlew assembleRelease
      - name: Run unit tests
        script: ./gradlew test
        test_report: app/build/testCICD.xml

    artifacts:
      - app/build/outputs/testCICD.apk
    environment:
      flutter: stable
      java: 1.8
